valid_plausible_diff_chain_C = {
    "AE1": ("All {A} are {B}.", "No {B} are {C}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AE3": ("All {A} are {B}.", "No {C} are {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AO3": ("All {A} are {B}.", "Some {C} are not {B}.", ["Some {C} are not {A}."]),
    "IE1": ("Some {A} are {B}.", "No {B} are {C}.", ["Some {A} are not {C}."]),
    "IE2": ("Some {B} are {A}.", "No {C} are {B}.", ["Some {A} are not {C}."]),
    "IE3": ("Some {A} are {B}.", "No {C} are {B}.", ["Some {A} are not {C}."]),
    "IE4": ("Some {B} are {A}.", "No {B} are {C}.", ["Some {A} are not {C}."])
}

valid_plausible_diff_chain_A ={
    "EA1": ("No {A} are {B}.", "All {B} are {C}.", ["Some {C} are not {A}."]),
    "EA4": ("No {B} are {A}.", "All {B} are {C}.", ["Some {C} are not {A}."]),
    "EI1": ("No {A} are {B}.", "Some {B} are {C}.", ["Some {C} are not {A}."]),
    "EI2": ("No {B} are {A}.", "Some {C} are {B}.", ["Some {C} are not {A}."]),
    "EI3": ("No {A} are {B}.", "Some {C} are {B}.", ["Some {C} are not {A}."]),
    "EI4": ("No {B} are {A}.", "Some {B} are {C}.", ["Some {C} are not {A}."]),
    "OA4": ("Some {B} are not {A}.", "All {B} are {C}.", ["Some {C} are not {A}."])
}

valid_plausible_same_chain = {
    "AA1": ("All {A} are {B}.", "All {B} are {C}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "AO3": ("All {A} are {B}.", "Some {C} are not {B}.", ["Some {C} are not {A}."]),
    "IA1": ("Some {A} are {B}.", "All {B} are {C}.", ["Some {A} are {C}.", "Some {C} are {A}."]),
    "IA4": ("Some {B} are {A}.", "All {B} are {C}.", ["Some {A} are {C}.", "Some {C} are {A}."]),
    "OA4": ("Some {B} are not {A}.", "All {B} are {C}.", ["Some {C} are not {A}."]),
}

invalid_plausible_same_chain = {
    "AI1": ("All {A} are {B}.", "Some {B} are {C}.", ["All {A} are {C}." , "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "AI3": ("All {A} are {B}.", "Some {C} are {B}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "II1": ("Some {A} are {B}.", "Some {B} are {C}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "II2": ("Some {B} are {A}.", "Some {C} are {B}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "II3": ("Some {A} are {B}.", "Some {C} are {B}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "II4": ("Some {B} are {A}.", "Some {B} are {C}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "IO2": ("Some {B} are {A}.", "Some {C} are not {B}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "IO3": ("Some {A} are {B}.", "Some {C} are not {B}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "OI2": ("Some {B} are not {A}.", "Some {C} are {B}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "OI4": ("Some {B} are not {A}.", "Some {B} are {C}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "OO2": ("Some {B} are not {A}.", "Some {C} are not {B}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "AA1": ("All {A} are {B}.", "All {B} are {C}.", ["Some {C} are not {A}."]),
    "AO3": ("All {A} are {B}.", "Some {C} are not {B}.", ["All {A} are {C}." , "Some {A} are {C}.", "Some {C} are {A}."]),
    "IA1": ("Some {A} are {B}.", "All {B} are {C}.", ["All {A} are {C}." , "Some {C} are not {A}."]),
    "IA4": ("Some {B} are {A}.", "All {B} are {C}.", ["All {A} are {C}." , "Some {C} are not {A}."]),
    "OA4": ("Some {B} are not {A}.", "All {B} are {C}.", ["All {A} are {C}." , "Some {A} are {C}.", "Some {C} are {A}."]),
}

invalid_plausible_diff_chain_C = {
    "AO1": ("All {A} are {B}.", "Some {B} are not {C}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "IO1": ("Some {A} are {B}.", "Some {B} are not {C}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "IO2": ("Some {B} are {A}.", "Some {C} are not {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "IO3": ("Some {A} are {B}.", "Some {C} are not {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "IO4": ("Some {B} are {A}.", "Some {B} are not {C}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OE2": ("Some {B} are not {A}.", "No {C} are {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OE4": ("Some {B} are not {A}.", "No {B} are {C}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OO2": ("Some {B} are not {A}.", "Some {C} are not {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OO4": ("Some {B} are not {A}.", "Some {B} are not {C}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AO3": ("All {A} are {B}.", "Some {C} are not {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "IE1": ("Some {A} are {B}.", "No {B} are {C}.", ["No {A} are {C}.", "No {C} are {A}.","Some {C} are not {A}."]),
    "IE2": ("Some {B} are {A}.", "No {C} are {B}.", ["No {A} are {C}.", "No {C} are {A}.","Some {C} are not {A}."]),
    "IE3": ("Some {A} are {B}.", "No {C} are {B}.", ["No {A} are {C}.", "No {C} are {A}.","Some {C} are not {A}."]),
    "IE4": ("Some {B} are {A}.", "No {B} are {C}.", ["No {A} are {C}.", "No {C} are {A}.","Some {C} are not {A}."])
}

invalid_plausible_diff_chain_B = {
        "EE1": ("No {A} are {B}.", "No {B} are {C}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
        "EE2": ("No {B} are {A}.", "No {C} are {B}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
        "EE3": ("No {A} are {B}.", "No {C} are {B}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
        "EE4": ("No {B} are {A}.", "No {B} are {C}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
        "EO1": ("No {A} are {B}.", "Some {B} are not {C}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
        "EO2": ("No {B} are {A}.", "Some {C} are not {B}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
        "EO3": ("No {A} are {B}.", "Some {C} are not {B}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
        "EO4": ("No {B} are {A}.", "Some {B} are not {C}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
        "OE1": ("Some {A} are not {B}.", "No {B} are {C}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
        "OE2": ("Some {B} are not {A}.", "No {C} are {B}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
        "OE3": ("Some {A} are not {B}.", "No {C} are {B}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
        "OE4": ("Some {B} are not {A}.", "No {B} are {C}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
        "OO1": ("Some {A} are not {B}.", "Some {B} are not {C}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
        "OO2": ("Some {B} are not {A}.", "Some {C} are not {B}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
        "OO3": ("Some {A} are not {B}.", "Some {C} are not {B}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
        "OO4": ("Some {B} are not {A}.", "Some {B} are not {C}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."])
}

invalid_plausible_diff_chain_A = {
        "EO2": ("No {B} are {A}.", "Some {C} are not {B}.", ["Some {A} are not {C}.", "Some {C} are not {A}.", "No {A} are {C}.", "No {C} are {A}."]),
        "EO3": ("No {A} are {B}.", "Some {C} are not {B}.", ["Some {A} are not {C}.", "Some {C} are not {A}.", "No {A} are {C}.", "No {C} are {A}."]),
        "OA1": ("Some {A} are not {B}.", "All {B} are {C}.", ["Some {A} are not {C}.", "Some {C} are not {A}.", "No {A} are {C}.", "No {C} are {A}."]),
        "OI1": ("Some {A} are not {B}.", "Some {B} are {C}.", ["Some {A} are not {C}.", "Some {C} are not {A}.", "No {A} are {C}.", "No {C} are {A}."]),
        "OI2": ("Some {B} are not {A}.", "Some {C} are {B}.", ["Some {A} are not {C}.", "Some {C} are not {A}.", "No {A} are {C}.", "No {C} are {A}."]),
        "OI3": ("Some {A} are not {B}.", "Some {C} are {B}.", ["Some {A} are not {C}.", "Some {C} are not {A}.", "No {A} are {C}.", "No {C} are {A}."]),
        "OI4": ("Some {B} are not {A}.", "Some {B} are {C}.", ["Some {A} are not {C}.", "Some {C} are not {A}.", "No {A} are {C}.", "No {C} are {A}."]),
        "OO2": ("Some {B} are not {A}.", "Some {C} are not {B}.", ["Some {A} are not {C}.", "Some {C} are not {A}.", "No {A} are {C}.", "No {C} are {A}."]),
        "OO3": ("Some {A} are not {B}.", "Some {C} are not {B}.", ["Some {A} are not {C}.", "Some {C} are not {A}.", "No {A} are {C}.", "No {C} are {A}."]), 
        "OA4": ("Some {B} are not {A}.", "All {B} are {C}.", ["Some {A} are not {C}.", "No {A} are {C}.", "No {C} are {A}."]),
        "EA1": ("No {A} are {B}.", "All {B} are {C}.", ["Some {A} are not {C}.", "No {A} are {C}.", "No {C} are {A}."]),
        "EA4": ("No {B} are {A}.", "All {B} are {C}.", ["Some {A} are not {C}.", "No {A} are {C}.", "No {C} are {A}."]),
        "EI1": ("No {A} are {B}.", "Some {B} are {C}.", ["Some {A} are not {C}.", "No {A} are {C}.", "No {C} are {A}."]),
        "EI2": ("No {B} are {A}.", "Some {C} are {B}.", ["Some {A} are not {C}.", "No {A} are {C}.", "No {C} are {A}."]),
        "EI3": ("No {A} are {B}.", "Some {C} are {B}.", ["Some {A} are not {C}.", "No {A} are {C}.", "No {C} are {A}."]),
        "EI4": ("No {B} are {A}.", "Some {B} are {C}.", ["Some {A} are not {C}.", "No {A} are {C}.", "No {C} are {A}."])
}

invalid_plausible_diff_chain = {
        "EE1": ("No {A} are {B}.", "No {B} are {C}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
        "EE2": ("No {B} are {A}.", "No {C} are {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
        "EE3": ("No {A} are {B}.", "No {C} are {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
        "EE4": ("No {B} are {A}.", "No {B} are {C}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
        "EO1": ("No {A} are {B}.", "Some {B} are not {C}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
        "EO2": ("No {B} are {A}.", "Some {C} are not {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
        "EO3": ("No {A} are {B}.", "Some {C} are not {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
        "EO4": ("No {B} are {A}.", "Some {B} are not {C}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
        "OE1": ("Some {A} are not {B}.", "No {B} are {C}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
        "OE2": ("Some {B} are not {A}.", "No {C} are {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
        "OE3": ("Some {A} are not {B}.", "No {C} are {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
        "OE4": ("Some {B} are not {A}.", "No {B} are {C}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
        "OO1": ("Some {A} are not {B}.", "Some {B} are not {C}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
        "OO2": ("Some {B} are not {A}.", "Some {C} are not {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
        "OO3": ("Some {A} are not {B}.", "Some {C} are not {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
        "OO4": ("Some {B} are not {A}.", "Some {B} are not {C}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."])
}

valid_implausible_same_chain = {
    "AA2": ("All {B} are {A}.", "All {C} are {B}.",
            ["All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "AA4": ("All {B} are {A}.", "All {B} are {C}.",
            ["Some {A} are {C}.", "Some {C} are {A}."]),
    "AI2": ("All {B} are {A}.", "Some {C} are {B}.",
            ["Some {A} are {C}.", "Some {C} are {A}."]),
    "AI4": ("All {B} are {A}.", "Some {B} are {C}.",
            ["Some {A} are {C}.", "Some {C} are {A}."]),
    "AE1": ("All {A} are {B}.", "No {B} are {C}.",
            ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AE2": ("All {B} are {A}.", "No {C} are {B}.",
            ["Some {A} are not {C}."]),
    "AE3": ("All {A} are {B}.", "No {C} are {B}.",
            ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AE4": ("All {B} are {A}.", "No {B} are {C}.",
            ["Some {A} are not {C}."]),
    "AO4": ("All {B} are {A}.", "Some {B} are not {C}.",
            ["Some {A} are not {C}."]),
    "IE1": ("Some {A} are {B}.", "No {B} are {C}.",
            ["Some {A} are not {C}."]),
    "IE2": ("Some {B} are {A}.", "No {C} are {B}.",
            ["Some {A} are not {C}."]),
    "IE3": ("Some {A} are {B}.", "No {C} are {B}.",
            ["Some {A} are not {C}."]),
    "IE4": ("Some {B} are {A}.", "No {B} are {C}.",
            ["Some {A} are not {C}."]),
    "EA1": ("No {A} are {B}.", "All {B} are {C}.",
            ["Some {C} are not {A}."]),
    "EA2": ("No {B} are {A}.", "All {C} are {B}.",
            ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EA3": ("No {A} are {B}.", "All {C} are {B}.",
            ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EA4": ("No {B} are {A}.", "All {B} are {C}.",
            ["Some {C} are not {A}."]),
    "EI1": ("No {A} are {B}.", "Some {B} are {C}.",
            ["Some {C} are not {A}."]),
    "EI2": ("No {B} are {A}.", "Some {C} are {B}.",
            ["Some {C} are not {A}."]),
    "EI3": ("No {A} are {B}.", "Some {C} are {B}.",
            ["Some {C} are not {A}."]),
    "EI4": ("No {B} are {A}.", "Some {B} are {C}.",
            ["Some {C} are not {A}."]),
    "OA3": ("Some {A} are not {B}.", "All {C} are {B}.",
            ["Some {A} are not {C}."])
}

valid_implausible_diff_chain_A = {
    "AA1": ("All {A} are {B}.", "All {B} are {C}.",
                ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "AA2": ("All {B} are {A}.", "All {C} are {B}.",
            ["All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "AA4": ("All {B} are {A}.", "All {B} are {C}.",
            ["Some {A} are {C}, Some {C} are {A}."]),
    "AI2": ("All {B} are {A}.", "Some {C} are {B}.",
            ["Some {A} are {C}.", "Some {C} are {A}."]),
    "AI4": ("All {B} are {A}.", "Some {B} are {C}.",
            ["Some {A} are {C}.", "Some {C} are {A}."]),
    "AE1": ("All {A} are {B}.", "No {B} are {C}.",
            ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AE2": ("All {B} are {A}.", "No {C} are {B}.",
            ["Some {A} are not {C}."]),
    "AE3": ("All {A} are {B}.", "No {C} are {B}.",
            ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AE4": ("All {B} are {A}.", "No {B} are {C}.",
            ["Some {A} are not {C}."]),
    "AO3": ("All {A} are {B}.", "Some {C} are not {B}.",
            ["Some {C} are not {A}."]),
    "AO4": ("All {B} are {A}.", "Some {B} are not {C}.",
            ["Some {A} are not {C}."]),
    "IA1": ("Some {A} are {B}.", "All {B} are {C}.",
            ["Some {A} are {C}.", "Some {C} are {A}."]),
    "IA4": ("Some {B} are {A}.", "All {B} are {C}.",
            ["Some {A} are {C}.", "Some {C} are {A}."]),
    "IE1": ("Some {A} are {B}.", "No {B} are {C}.",
            ["Some {A} are not {C}."]),
    "IE2": ("Some {B} are {A}.", "No {C} are {B}.",
            ["Some {A} are not {C}."]),
    "IE3": ("Some {A} are {B}.", "No {C} are {B}.",
            ["Some {A} are not {C}."]),
    "IE4": ("Some {B} are {A}.", "No {B} are {C}.",
            ["Some {A} are not {C}."]),
    "EA2": ("No {B} are {A}.", "All {C} are {B}.",
            ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EA3": ("No {A} are {B}.", "All {C} are {B}.",
            ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OA3": ("Some {A} are not {B}.", "All {C} are {B}.",
            ["Some {A} are not {C}."]),
}

valid_implausible_diff_chain_B = {
    "AA1": ("All {A} are {B}.", "All {B} are {C}.",
                ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "AA2": ("All {B} are {A}.", "All {C} are {B}.",
            ["All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "AA4": ("All {B} are {A}.", "All {B} are {C}.",
            ["Some {A} are {C}, Some {C} are {A}."]),
    "AI2": ("All {B} are {A}.", "Some {C} are {B}.",
            ["Some {A} are {C}.", "Some {C} are {A}."]),
    "AI4": ("All {B} are {A}.", "Some {B} are {C}.",
            ["Some {A} are {C}.", "Some {C} are {A}."]),
    "AE1": ("All {A} are {B}.", "No {B} are {C}.",
            ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AE2": ("All {B} are {A}.", "No {C} are {B}.",
            ["Some {A} are not {C}."]),
    "AE3": ("All {A} are {B}.", "No {C} are {B}.",
            ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AE4": ("All {B} are {A}.", "No {B} are {C}.",
            ["Some {A} are not {C}."]),
    "AO3": ("All {A} are {B}.", "Some {C} are not {B}.",
            ["Some {C} are not {A}."]),
    "AO4": ("All {B} are {A}.", "Some {B} are not {C}.",
            ["Some {A} are not {C}."]),
    "IA1": ("Some {A} are {B}.", "All {B} are {C}.",
            ["Some {A} are {C}.", "Some {C} are {A}."]),
    "IA4": ("Some {B} are {A}.", "All {B} are {C}.",
            ["Some {A} are {C}.", "Some {C} are {A}."]),
    "IE1": ("Some {A} are {B}.", "No {B} are {C}.",
            ["Some {A} are not {C}."]),
    "IE2": ("Some {B} are {A}.", "No {C} are {B}.",
            ["Some {A} are not {C}."]),
    "IE3": ("Some {A} are {B}.", "No {C} are {B}.",
            ["Some {A} are not {C}."]),
    "IE4": ("Some {B} are {A}.", "No {B} are {C}.",
            ["Some {A} are not {C}."]),
    "EA1": ("No {A} are {B}.", "All {B} are {C}.",
            ["Some {C} are not {A}."]),
    "EA2": ("No {B} are {A}.", "All {C} are {B}.",
            ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EA3": ("No {A} are {B}.", "All {C} are {B}.",
            ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EA4": ("No {B} are {A}.", "All {B} are {C}.",
            ["Some {C} are not {A}."]),
    "EI1": ("No {A} are {B}.", "Some {B} are {C}.",
            ["Some {C} are not {A}."]),
    "EI2": ("No {B} are {A}.", "Some {C} are {B}.",
            ["Some {C} are not {A}."]),
    "EI3": ("No {A} are {B}.", "Some {C} are {B}.",
            ["Some {C} are not {A}."]),
    "EI4": ("No {B} are {A}.", "Some {B} are {C}.",
            ["Some {C} are not {A}."]),
    "OA3": ("Some {A} are not {B}.", "All {C} are {B}.",
            ["Some {A} are not {C}."]),
    "OA4": ("Some {B} are not {A}.", "All {B} are {C}.",
            ["Some {C} are not {A}."])
}

valid_implausible_diff_chain_C = {
    "AA1": ("All {A} are {B}.", "All {B} are {C}.",
                ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "AA2": ("All {B} are {A}.", "All {C} are {B}.",
            ["All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "AA4": ("All {B} are {A}.", "All {B} are {C}.",
            ["Some {A} are {C}, Some {C} are {A}."]),
    "AI2": ("All {B} are {A}.", "Some {C} are {B}.",
            ["Some {A} are {C}.", "Some {C} are {A}."]),
    "AI4": ("All {B} are {A}.", "Some {B} are {C}.",
            ["Some {A} are {C}.", "Some {C} are {A}."]),
    "IA1": ("Some {A} are {B}.", "All {B} are {C}.",
            ["Some {A} are {C}.", "Some {C} are {A}."]),
    "IA4": ("Some {B} are {A}.", "All {B} are {C}.",
            ["Some {A} are {C}.", "Some {C} are {A}."]),
    "EA1": ("No {A} are {B}.", "All {B} are {C}.",
            ["Some {C} are not {A}."]),
    "EA2": ("No {B} are {A}.", "All {C} are {B}.",
            ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EA3": ("No {A} are {B}.", "All {C} are {B}.",
            ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EA4": ("No {B} are {A}.", "All {B} are {C}.",
            ["Some {C} are not {A}."]),
    "EI1": ("No {A} are {B}.", "Some {B} are {C}.",
            ["Some {C} are not {A}."]),
    "EI2": ("No {B} are {A}.", "Some {C} are {B}.",
            ["Some {C} are not {A}."]),
    "EI3": ("No {A} are {B}.", "Some {C} are {B}.",
            ["Some {C} are not {A}."]),
    "EI4": ("No {B} are {A}.", "Some {B} are {C}.",
            ["Some {C} are not {A}."]),
    "OA3": ("Some {A} are not {B}.", "All {C} are {B}.",
            ["Some {A} are not {C}."]),
    "OA4": ("Some {B} are not {A}.", "All {B} are {C}.",
            ["Some {C} are not {A}."])
}

invalid_implausible_same_chain = {
    "AA3": ("All {A} are {B}.", "All {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AI1": ("All {A} are {B}.", "Some {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "AI3": ("All {A} are {B}.", "Some {C} are {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "AO1": ("All {A} are {B}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AO2": ("All {B} are {A}.", "Some {C} are not {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "IA2": ("Some {B} are {A}.", "All {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "IA3": ("Some {A} are {B}.", "All {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "II1": ("Some {A} are {B}.", "Some {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "II2": ("Some {B} are {A}.", "Some {C} are {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "II3": ("Some {A} are {B}.", "Some {C} are {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "II4": ("Some {B} are {A}.", "Some {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),

    "IO1": ("Some {A} are {B}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "IO2": ("Some {B} are {A}.", "Some {C} are not {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "IO3": ("Some {A} are {B}.", "Some {C} are not {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "IO4": ("Some {B} are {A}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "EE1": ("No {A} are {B}.", "No {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EE2": ("No {B} are {A}.", "No {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EE3": ("No {A} are {B}.", "No {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EE4": ("No {B} are {A}.", "No {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "EO1": ("No {A} are {B}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EO2": ("No {B} are {A}.", "Some {C} are not {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EO3": ("No {A} are {B}.", "Some {C} are not {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EO4": ("No {B} are {A}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "OA1": ("Some {A} are not {B}.", "All {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OA2": ("Some {B} are not {A}.", "All {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "OI1": ("Some {A} are not {B}.", "Some {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OI2": ("Some {B} are not {A}.", "Some {C} are {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "OI3": ("Some {A} are not {B}.", "Some {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OI4": ("Some {B} are not {A}.", "Some {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),

    "OE1": ("Some {A} are not {B}.", "No {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OE2": ("Some {B} are not {A}.", "No {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OE3": ("Some {A} are not {B}.", "No {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OE4": ("Some {B} are not {A}.", "No {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "OO1": ("Some {A} are not {B}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OO2": ("Some {B} are not {A}.", "Some {C} are not {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "OO3": ("Some {A} are not {B}.", "Some {C} are not {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OO4": ("Some {B} are not {A}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AA2": ("All {B} are {A}.", "All {C} are {B}.",
            ["All {A} are {C}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AA4": ("All {B} are {A}.", "All {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AI2": ("All {B} are {A}.", "Some {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AI4": ("All {B} are {A}.", "Some {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AE1": ("All {A} are {B}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "AE2": ("All {B} are {A}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "AE3": ("All {A} are {B}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.","Some {A} are {C}.", "Some {C} are {A}."]),
    "AE4": ("All {B} are {A}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "AO4": ("All {B} are {A}.", "Some {B} are not {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "IE1": ("Some {A} are {B}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "IE2": ("Some {B} are {A}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "IE3": ("Some {A} are {B}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "IE4": ("Some {B} are {A}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "EA1": ("No {A} are {B}.", "All {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}."]),
    "EA2": ("No {B} are {A}.", "All {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "EA3": ("No {A} are {B}.", "All {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.","Some {A} are {C}.", "Some {C} are {A}."]),
    "EA4": ("No {B} are {A}.", "All {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}."]),
    "EI1": ("No {A} are {B}.", "Some {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}."]),
    "EI2": ("No {B} are {A}.", "Some {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}."]),
    "EI3": ("No {A} are {B}.", "Some {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}."]),
    "EI4": ("No {B} are {A}.", "Some {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}."]),
    "OA3": ("Some {A} are not {B}.", "All {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."])
}

invalid_implausible_diff_chain_A = {
    "AA3": ("All {A} are {B}.", "All {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AI1": ("All {A} are {B}.", "Some {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "AI3": ("All {A} are {B}.", "Some {C} are {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "AO1": ("All {A} are {B}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AO2": ("All {B} are {A}.", "Some {C} are not {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "IA2": ("Some {B} are {A}.", "All {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "IA3": ("Some {A} are {B}.", "All {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "II1": ("Some {A} are {B}.", "Some {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "II2": ("Some {B} are {A}.", "Some {C} are {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "II3": ("Some {A} are {B}.", "Some {C} are {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "II4": ("Some {B} are {A}.", "Some {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),

    "IO1": ("Some {A} are {B}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "IO2": ("Some {B} are {A}.", "Some {C} are not {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "IO3": ("Some {A} are {B}.", "Some {C} are not {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "IO4": ("Some {B} are {A}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "EE1": ("No {A} are {B}.", "No {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EE2": ("No {B} are {A}.", "No {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EE3": ("No {A} are {B}.", "No {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EE4": ("No {B} are {A}.", "No {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "EO1": ("No {A} are {B}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EO2": ("No {B} are {A}.", "Some {C} are not {B}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "EO3": ("No {A} are {B}.", "Some {C} are not {B}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "EO4": ("No {B} are {A}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "OA1": ("Some {A} are not {B}.", "All {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "OA2": ("Some {B} are not {A}.", "All {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "OI1": ("Some {A} are not {B}.", "Some {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "OI2": ("Some {B} are not {A}.", "Some {C} are {B}.", ["All {C} are {A}."]),
    "OI3": ("Some {A} are not {B}.", "Some {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "OI4": ("Some {B} are not {A}.", "Some {B} are {C}.", ["All {C} are {A}."]),

    "OE1": ("Some {A} are not {B}.", "No {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OE2": ("Some {B} are not {A}.", "No {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OE3": ("Some {A} are not {B}.", "No {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OE4": ("Some {B} are not {A}.", "No {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "OO1": ("Some {A} are not {B}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OO2": ("Some {B} are not {A}.", "Some {C} are not {B}.", ["All {C} are {A}."]),
    "OO3": ("Some {A} are not {B}.", "Some {C} are not {B}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "OO4": ("Some {B} are not {A}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AA1": ("All {A} are {B}.", "All {B} are {C}.",
                ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AA2": ("All {B} are {A}.", "All {C} are {B}.",
            ["All {A} are {C}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AA4": ("All {B} are {A}.", "All {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AI2": ("All {B} are {A}.", "Some {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AI4": ("All {B} are {A}.", "Some {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AE1": ("All {A} are {B}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "AE2": ("All {B} are {A}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "AE3": ("All {A} are {B}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.","Some {A} are {C}.", "Some {C} are {A}."]),
    "AE4": ("All {B} are {A}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "AO3": ("All {A} are {B}.", "Some {C} are not {B}.",
            ["Some {A} are not {C}.", "All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "AO4": ("All {B} are {A}.", "Some {B} are not {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "IA1": ("Some {A} are {B}.", "All {B} are {C}.",
            ["Some {A} are not {C}.", "Some {C} are not {A}.", "All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}."]),
    "IA4": ("Some {B} are {A}.", "All {B} are {C}.",
            ["Some {A} are not {C}.", "Some {C} are not {A}.", "All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}."]),
    "IE1": ("Some {A} are {B}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "IE2": ("Some {B} are {A}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "IE3": ("Some {A} are {B}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "IE4": ("Some {B} are {A}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "EA1": ("No {A} are {B}.", "All {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "EA2": ("No {B} are {A}.", "All {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "EA3": ("No {A} are {B}.", "All {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.","Some {A} are {C}.", "Some {C} are {A}."]),
    "EA4": ("No {B} are {A}.", "All {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "EI1": ("No {A} are {B}.", "Some {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "EI2": ("No {B} are {A}.", "Some {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "EI3": ("No {A} are {B}.", "Some {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "EI4": ("No {B} are {A}.", "Some {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "OA3": ("Some {A} are not {B}.", "All {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."])
}

invalid_implausible_diff_chain_B = {
    "AA3": ("All {A} are {B}.", "All {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AI1": ("All {A} are {B}.", "Some {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "AI3": ("All {A} are {B}.", "Some {C} are {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "AO1": ("All {A} are {B}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AO2": ("All {B} are {A}.", "Some {C} are not {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "IA2": ("Some {B} are {A}.", "All {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "IA3": ("Some {A} are {B}.", "All {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "II1": ("Some {A} are {B}.", "Some {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "II2": ("Some {B} are {A}.", "Some {C} are {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "II3": ("Some {A} are {B}.", "Some {C} are {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "II4": ("Some {B} are {A}.", "Some {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),

    "IO1": ("Some {A} are {B}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "IO2": ("Some {B} are {A}.", "Some {C} are not {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "IO3": ("Some {A} are {B}.", "Some {C} are not {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "IO4": ("Some {B} are {A}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "EE1": ("No {A} are {B}.", "No {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "EE2": ("No {B} are {A}.", "No {C} are {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "EE3": ("No {A} are {B}.", "No {C} are {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "EE4": ("No {B} are {A}.", "No {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),

    "EO1": ("No {A} are {B}.", "Some {B} are not {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "EO2": ("No {B} are {A}.", "Some {C} are not {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "EO3": ("No {A} are {B}.", "Some {C} are not {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "EO4": ("No {B} are {A}.", "Some {B} are not {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),

    "OA1": ("Some {A} are not {B}.", "All {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OA2": ("Some {B} are not {A}.", "All {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "OI1": ("Some {A} are not {B}.", "Some {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OI2": ("Some {B} are not {A}.", "Some {C} are {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "OI3": ("Some {A} are not {B}.", "Some {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OI4": ("Some {B} are not {A}.", "Some {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),

    "OE1": ("Some {A} are not {B}.", "No {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "OE2": ("Some {B} are not {A}.", "No {C} are {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "OE3": ("Some {A} are not {B}.", "No {C} are {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "OE4": ("Some {B} are not {A}.", "No {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),

    "OO1": ("Some {A} are not {B}.", "Some {B} are not {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "OO2": ("Some {B} are not {A}.", "Some {C} are not {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "OO3": ("Some {A} are not {B}.", "Some {C} are not {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "OO4": ("Some {B} are not {A}.", "Some {B} are not {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "AA1": ("All {A} are {B}.", "All {B} are {C}.",
                ["All {C} are {A}.","No {A} are {C}.","No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AA2": ("All {B} are {A}.", "All {C} are {B}.",
            ["All {A} are {C}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AA4": ("All {B} are {A}.", "All {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AI2": ("All {B} are {A}.", "Some {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AI4": ("All {B} are {A}.", "Some {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AE1": ("All {A} are {B}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "AE2": ("All {B} are {A}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "AE3": ("All {A} are {B}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.","Some {A} are {C}.", "Some {C} are {A}."]),
    "AE4": ("All {B} are {A}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "AO3": ("All {A} are {B}.", "Some {C} are not {B}.",
            ["All {A} are {C}.", "All {C} are {A}.","No {A} are {C}.", "No {C} are {A}.","Some {A} are {C}.", "Some {C} are {A}.","Some {A} are not {C}."]),
    "IA1": ("Some {A} are {B}.", "All {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "IA4": ("Some {B} are {A}.", "All {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AO4": ("All {B} are {A}.", "Some {B} are not {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "IE1": ("Some {A} are {B}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "IE2": ("Some {B} are {A}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "IE3": ("Some {A} are {B}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "IE4": ("Some {B} are {A}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "EA1": ("No {A} are {B}.", "All {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}."]),
    "EA2": ("No {B} are {A}.", "All {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "EA3": ("No {A} are {B}.", "All {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.","Some {A} are {C}.", "Some {C} are {A}."]),
    "EA4": ("No {B} are {A}.", "All {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}."]),
    "EI1": ("No {A} are {B}.", "Some {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}."]),
    "EI2": ("No {B} are {A}.", "Some {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}."]),
    "EI3": ("No {A} are {B}.", "Some {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}."]),
    "EI4": ("No {B} are {A}.", "Some {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}."]),
    "OA3": ("Some {A} are not {B}.", "All {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "OA4": ("Some {B} are not {A}.", "All {B} are {C}.",
            ["All {A} are {C}.","All {C} are {A}.","No {A} are {C}.","No {C} are {A}.","Some {A} are {C}.","Some {C} are {A}.","Some {A} are not {C}."])
}

invalid_implausible_diff_chain_C = {
    "AA3": ("All {A} are {B}.", "All {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AI1": ("All {A} are {B}.", "Some {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "AI3": ("All {A} are {B}.", "Some {C} are {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "AO1": ("All {A} are {B}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "AO2": ("All {B} are {A}.", "Some {C} are not {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "IA2": ("Some {B} are {A}.", "All {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "IA3": ("Some {A} are {B}.", "All {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "II1": ("Some {A} are {B}.", "Some {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "II2": ("Some {B} are {A}.", "Some {C} are {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "II3": ("Some {A} are {B}.", "Some {C} are {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "II4": ("Some {B} are {A}.", "Some {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),

    "IO1": ("Some {A} are {B}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "IO2": ("Some {B} are {A}.", "Some {C} are not {B}.", ["All {C} are {A}."]),
    "IO3": ("Some {A} are {B}.", "Some {C} are not {B}.", ["All {C} are {A}."]),
    "IO4": ("Some {B} are {A}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),

    "EE1": ("No {A} are {B}.", "No {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EE2": ("No {B} are {A}.", "No {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EE3": ("No {A} are {B}.", "No {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EE4": ("No {B} are {A}.", "No {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "EO1": ("No {A} are {B}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EO2": ("No {B} are {A}.", "Some {C} are not {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EO3": ("No {A} are {B}.", "Some {C} are not {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "EO4": ("No {B} are {A}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "OA1": ("Some {A} are not {B}.", "All {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OA2": ("Some {B} are not {A}.", "All {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),

    "OI1": ("Some {A} are not {B}.", "Some {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OI2": ("Some {B} are not {A}.", "Some {C} are {B}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "OI3": ("Some {A} are not {B}.", "Some {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OI4": ("Some {B} are not {A}.", "Some {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),

    "OE1": ("Some {A} are not {B}.", "No {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OE2": ("Some {B} are not {A}.", "No {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "OE3": ("Some {A} are not {B}.", "No {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OE4": ("Some {B} are not {A}.", "No {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),

    "OO1": ("Some {A} are not {B}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OO2": ("Some {B} are not {A}.", "Some {C} are not {B}.", ["All {C} are {A}."]),
    "OO3": ("Some {A} are not {B}.", "Some {C} are not {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "OO4": ("Some {B} are not {A}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "AA1": ("All {A} are {B}.", "All {B} are {C}.",
                ["All {C} are {A}.","No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AA2": ("All {B} are {A}.", "All {C} are {B}.",
            ["All {A} are {C}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AA4": ("All {B} are {A}.", "All {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AI2": ("All {B} are {A}.", "Some {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AI4": ("All {B} are {A}.", "Some {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "IA1": ("Some {A} are {B}.", "All {B} are {C}.",
            ["All {A} are {C}.","All {C} are {A}.", "No {A} are {C}.","No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "IA4": ("Some {B} are {A}.", "All {B} are {C}.",
            ["All {A} are {C}.","All {C} are {A}.", "No {A} are {C}.","No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AE1": ("All {A} are {B}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "AE2": ("All {B} are {A}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "AE3": ("All {A} are {B}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.","Some {A} are {C}.", "Some {C} are {A}."]),
    "AE4": ("All {B} are {A}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "AO4": ("All {B} are {A}.", "Some {B} are not {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "IE1": ("Some {A} are {B}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "IE2": ("Some {B} are {A}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "IE3": ("Some {A} are {B}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "IE4": ("Some {B} are {A}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "EA1": ("No {A} are {B}.", "All {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}."]),
    "EA2": ("No {B} are {A}.", "All {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "EA3": ("No {A} are {B}.", "All {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.","Some {A} are {C}.", "Some {C} are {A}."]),
    "EA4": ("No {B} are {A}.", "All {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}."]),
    "EI1": ("No {A} are {B}.", "Some {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}."]),
    "EI2": ("No {B} are {A}.", "Some {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}."]),
    "EI3": ("No {A} are {B}.", "Some {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}."]),
    "EI4": ("No {B} are {A}.", "Some {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}."]),
    "OA3": ("Some {A} are not {B}.", "All {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "OA4": ("Some {B} are not {A}.", "All {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.","No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.","Some {A} are not {C}."])
}

valid_implausible_diff_chain = {
   "AA1": ("All {A} are {B}.", "All {B} are {C}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}."]),
   "AA2": ("All {B} are {A}.", "All {C} are {B}.", ["All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
   "AA4": ("All {B} are {A}.", "All {B} are {C}.", ["Some {A} are {C}.", "Some {C} are {A}."]),
   "AI2": ("All {B} are {A}.", "Some {C} are {B}.",["Some {A} are {C}.", "Some {C} are {A}."]),
   "AI4": ("All {B} are {A}.", "Some {B} are {C}.", ["Some {A} are {C}.", "Some {C} are {A}."]),
   "AE1": ("All {A} are {B}.", "No {B} are {C}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
   "AE2": ("All {B} are {A}.", "No {C} are {B}.", ["Some {A} are not {C}."]),
   "AE3": ("All {A} are {B}.", "No {C} are {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
   "AE4": ("All {B} are {A}.", "No {B} are {C}.", ["Some {A} are not {C}."]),
   "AO3": ("All {A} are {B}.", "Some {C} are not {B}.", ["Some {C} are not {A}."]),
   "AO4": ("All {B} are {A}.", "Some {B} are not {C}.", ["Some {A} are not {C}."]),
   "IA1": ("Some {A} are {B}.", "All {B} are {C}.", ["Some {A} are {C}.", "Some {C} are {A}."]),
   "IA4": ("Some {B} are {A}.", "All {B} are {C}.", ["Some {A} are {C}.", "Some {C} are {A}."]),
   "IE1": ("Some {A} are {B}.", "No {B} are {C}.", ["Some {A} are not {C}."]),
   "IE2": ("Some {B} are {A}.", "No {C} are {B}.", ["Some {A} are not {C}."]),
   "IE3": ("Some {A} are {B}.", "No {C} are {B}.", ["Some {A} are not {C}."]),
   "IE4": ("Some {B} are {A}.", "No {B} are {C}.", ["Some {A} are not {C}."]),
   "EA1": ("No {A} are {B}.", "All {B} are {C}.", ["Some {C} are not {A}."]),
   "EA2": ("No {B} are {A}.", "All {C} are {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
   "EA3": ("No {A} are {B}.", "All {C} are {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
   "EA4": ("No {B} are {A}.", "All {B} are {C}.", ["Some {C} are not {A}."]),
   "EI1": ("No {A} are {B}.", "Some {B} are {C}.", ["Some {C} are not {A}."]),
   "EI2": ("No {B} are {A}.", "Some {C} are {B}.", ["Some {C} are not {A}."]),
   "EI3": ("No {A} are {B}.", "Some {C} are {B}.", ["Some {C} are not {A}."]),
   "EI4": ("No {B} are {A}.", "Some {B} are {C}.", ["Some {C} are not {A}."]),
   "OA3": ("Some {A} are not {B}.", "All {C} are {B}.", ["Some {A} are not {C}."]),
   "OA4": ("Some {B} are not {A}.", "All {B} are {C}.", ["Some {C} are not {A}."])
}

invalid_implausible_diff_chain = {
    "AA1": ("All {A} are {B}.", "All {B} are {C}.", ["All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AA2": ("All {B} are {A}.", "All {C} are {B}.", ["All {A} are {C}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AA4": ("All {B} are {A}.", "All {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AI2": ("All {B} are {A}.", "Some {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AI4": ("All {B} are {A}.", "Some {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "AE1": ("All {A} are {B}.", "No {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "AE2": ("All {B} are {A}.", "No {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "AE3": ("All {A} are {B}.", "No {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "AE4": ("All {B} are {A}.", "No {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}."]),
    "AO3": ("All {A} are {B}.", "Some {C} are not {B}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "AO4": ("All {B} are {A}.", "Some {B} are not {C}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {C} are not {A}."]),
    "IA1": ("Some {A} are {B}.", "All {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "IA4": ("Some {B} are {A}.", "All {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
    "IE1": ("Some {A} are {B}.", "No {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {C} are not {A}."]),
    "IE2": ("Some {B} are {A}.", "No {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {C} are not {A}."]),
    "IE3": ("Some {A} are {B}.", "No {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {C} are not {A}."]),
    "IE4": ("Some {B} are {A}.", "No {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {C} are not {A}."]),
    "EA1": ("No {A} are {B}.", "All {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "EA2": ("No {B} are {A}.", "All {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "EA3": ("No {A} are {B}.", "All {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
    "EA4": ("No {B} are {A}.", "All {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "EI1": ("No {A} are {B}.", "Some {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "EI2": ("No {B} are {A}.", "Some {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "EI3": ("No {A} are {B}.", "Some {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "EI4": ("No {B} are {A}.", "Some {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}."]),
    "OA3": ("Some {A} are not {B}.", "All {C} are {B}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {C} are not {A}.", "No {A} are {C}.", "No {C} are {A}."]),
    "OA4": ("Some {B} are not {A}.", "All {B} are {C}.", ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "No {A} are {C}.", "No {C} are {A}."]),
    "AA3": ("All {A} are {B}.", "All {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

    "AI1": ("All {A} are {B}.", "Some {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

    "AI3": ("All {A} are {B}.", "Some {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

    "AO1": ("All {A} are {B}.", "Some {B} are not {C}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

    "AO2": ("All {B} are {A}.", "Some {C} are not {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

    "IA2": ("Some {B} are {A}.", "All {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

    "IA3": ("Some {A} are {B}.", "All {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

    "II1": ("Some {A} are {B}.", "Some {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

    "II2": ("Some {B} are {A}.", "Some {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

    "II3": ("Some {A} are {B}.", "Some {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

    "II4": ("Some {B} are {A}.", "Some {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

    "IO1": ("Some {A} are {B}.", "Some {B} are not {C}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

    "IO2": ("Some {A} are {B}.", "Some {C} are not {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

    "IO3": ("Some {A} are {B}.", "Some {C} are not {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

    "IO4": ("Some {B} are {A}.", "Some {C} are not {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

    "OA1": ("Some {A} are not {B}.", "All {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

    "OA2": ("Some {B} are not {A}.", "All {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

     "OI1": ("Some {A} are not {B}.", "Some {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

    "OI2": ("Some {B} are not {A}.", "Some {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

    "OI3": ("Some {A} are not {B}.", "Some {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),

    "OI4": ("Some {B} are not {A}.", "Some {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}.",
             "Some {A} are not {C}.", "Some {C} are not {A}.",
             "No {A} are {C}.", "No {C} are {A}."]),
             #seperator
    "EE1": ("No {A} are {B}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}."]),

    "EE2": ("No {B} are {A}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}."]),

    "EE3": ("No {A} are {B}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}."]),

    "EE4": ("No {B} are {A}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}."]),

    "EO1": ("No {A} are {B}.", "Some {B} are not {C}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}."]),

    "EO2": ("No {B} are {A}.", "Some {C} are not {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}."]),

    "EO3": ("No {A} are {B}.", "Some {C} are not {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}."]),

    "EO4": ("No {B} are {A}.", "Some {B} are not {C}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}."]),

    "OE1": ("Some {A} are not {B}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}."]),

    "OE2": ("Some {B} are not {A}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}."]),

    "OE3": ("Some {A} are not {B}.", "No {C} are {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}."]),

    "OE4": ("Some {B} are not {A}.", "No {B} are {C}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}."]),

    "OO1": ("Some {A} are not {B}.", "Some {B} are not {C}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}."]),

    "OO2": ("Some {B} are not {A}.", "Some {C} are not {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}."]),

    "OO3": ("Some {A} are not {B}.", "Some {C} are not {B}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}."]),

    "OO4": ("Some {B} are not {A}.", "Some {B} are not {C}.",
            ["All {A} are {C}.", "All {C} are {A}.",
             "Some {A} are {C}.", "Some {C} are {A}."])
}


valid_schemas = {
     "AA1": ("All {A} are {B}.", "All {B} are {C}.", ["All {A} are {C}.", "Some {A} are {C}.", "Some {C} are {A}."]),
     "AA2": ("All {B} are {A}.", "All {C} are {B}.", ["All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}."]),
     "AA4": ("All {B} are {A}.", "All {B} are {C}.", ["Some {A} are {C}.", "Some {C} are {A}."]),
     "AI2": ("All {B} are {A}.", "Some {C} are {B}.", ["Some {A} are {C}.", "Some {C} are {A}."]),
     "AI4": ("All {B} are {A}.", "Some {B} are {C}.", ["Some {A} are {C}.", "Some {C} are {A}."]),
     "AE1": ("All {A} are {B}.", "No {B} are {C}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
     "AE2": ("All {B} are {A}.", "No {C} are {B}.", ["Some {A} are not {C}."]),
     "AE3": ("All {A} are {B}.", "No {C} are {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
     "AE4": ("All {B} are {A}.", "No {B} are {C}.", ["Some {A} are not {C}."]),
     "AO3": ("All {A} are {B}.", "Some {C} are not {B}.", ["Some {C} are not {A}."]),
     "AO4": ("All {B} are {A}.", "Some {B} are not {C}.", ["Some {A} are not {C}."]),
     "IA1": ("Some {A} are {B}.", "All {B} are {C}.", ["Some {A} are {C}.", "Some {C} are {A}."]),
     "IA4": ("Some {B} are {A}.", "All {B} are {C}.", ["Some {A} are {C}.", "Some {C} are {A}."]),
     "IE1": ("Some {A} are {B}.", "No {B} are {C}.", ["Some {A} are not {C}."]),
     "IE2": ("Some {B} are {A}.", "No {B} are {C}.", ["Some {A} are not {C}."]),
     "IE3": ("Some {A} are {B}.", "No {C} are {B}.", ["Some {A} are not {C}."]),
     "IE4": ("Some {B} are {A}.", "No {C} are {B}.", ["Some {A} are not {C}."]),
     "EA1": ("No {A} are {B}.", "All {B} are {C}.", ["Some {C} are not {A}."]),
     "EA2": ("No {B} are {A}.", "All {C} are {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
     "EA3": ("No {A} are {B}.", "All {C} are {B}.", ["No {A} are {C}.", "No {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}."]),
     "EA4": ("No {B} are {A}.", "All {B} are {C}.", ["Some {C} are not {A}."]),
     "EI1": ("No {A} are {B}.", "Some {B} are {C}.", ["Some {C} are not {A}."]),
     "EI2": ("No {B} are {A}.", "Some {C} are {B}.", ["Some {C} are not {A}."]),
     "EI3": ("No {A} are {B}.", "Some {C} are {B}.", ["Some {C} are not {A}."]),
     "EI4": ("No {B} are {A}.", "Some {B} are {C}.", ["Some {C} are not {A}."]),
     "OA3": ("Some {A} are not {B}.", "All {C} are {B}.", ["Some {A} are not {C}."]),
     "OA4": ("Some {B} are not {A}.", "All {B} are {C}.", ["Some {C} are not {A}."])
}



all_possible_conclusions = ["All {A} are {C}.", "All {C} are {A}.", "Some {A} are {C}.", "Some {C} are {A}.", "Some {A} are not {C}.", "Some {C} are not {A}.", "No {A} are {C}.", "No {C} are {A}."]


invalid_schemas = {
     "AA3": ("All {A} are {B}.", "All {C} are {B}.", all_possible_conclusions),
     "AI1": ("All {A} are {B}.", "Some {B} are {C}.", all_possible_conclusions),
     "AI3": ("All {A} are {B}.", "Some {C} are {B}.", all_possible_conclusions),
     "AO1": ("All {A} are {B}.", "Some {B} are not {C}.", all_possible_conclusions),
     "AO2": ("All {B} are {A}.", "Some {C} are not {B}.", all_possible_conclusions),
     "IA2": ("Some {B} are {A}.", "All {C} are {B}.", all_possible_conclusions),
     "IA3": ("Some {A} are {B}.", "All {C} are {B}.", all_possible_conclusions),
     "II1": ("Some {A} are {B}.", "Some {B} are {C}.", all_possible_conclusions),
     "II2": ("Some {B} are {A}.", "Some {C} are {B}.", all_possible_conclusions),
     "II3": ("Some {A} are {B}.", "Some {C} are {B}.", all_possible_conclusions),
     "II4": ("Some {B} are {A}.", "Some {B} are {C}.", all_possible_conclusions),
     "IO1": ("Some {A} are {B}.", "Some {B} are not {C}.", all_possible_conclusions),
     "IO2": ("Some {B} are {A}.", "Some {C} are not {B}.", all_possible_conclusions),
     "IO3": ("Some {A} are {B}.", "Some {C} are not {B}.", all_possible_conclusions),
     "IO4": ("Some {B} are {A}.", "Some {B} are not {C}.", all_possible_conclusions),
     "EE1": ("No {A} are {B}.", "No {B} are {C}.", all_possible_conclusions),
     "EE2": ("No {B} are {A}.", "No {C} are {B}.", all_possible_conclusions),
     "EE3": ("No {A} are {B}.", "No {C} are {B}.", all_possible_conclusions),
     "EE4": ("No {B} are {A}.", "No {B} are {C}.", all_possible_conclusions),
     "EO1": ("No {A} are {B}.", "Some {B} are not {C}.", all_possible_conclusions),
     "EO2": ("No {B} are {A}.", "Some {C} are not {B}.", all_possible_conclusions),
     "EO3": ("No {A} are {B}.", "Some {C} are not {B}.", all_possible_conclusions),
     "EO4": ("No {B} are {A}.", "Some {B} are not {C}.", all_possible_conclusions),
     "OA1": ("Some {A} are not {B}.", "All {B} are {C}.", all_possible_conclusions),
     "OA2": ("Some {B} are not {A}.", "All {C} are {B}.", all_possible_conclusions),
     "OI1": ("Some {A} are not {B}.", "Some {B} are {C}.", all_possible_conclusions),
     "OI2": ("Some {B} are not {A}.", "Some {C} are {B}.", all_possible_conclusions),
     "OI3": ("Some {A} are not {B}.", "Some {C} are {B}.", all_possible_conclusions),
     "OI4": ("Some {B} are not {A}.", "Some {B} are {C}.", all_possible_conclusions),
     "OE1": ("Some {A} are not {B}.", "No {B} are {C}.", all_possible_conclusions),
     "OE2": ("Some {B} are not {A}.", "No {C} are {B}.", all_possible_conclusions),
     "OE3": ("Some {A} are not {B}.", "No {C} are {B}.", all_possible_conclusions),
     "OE4": ("Some {B} are not {A}.", "No {B} are {C}.", all_possible_conclusions),
     "OO1": ("Some {A} are not {B}.", "Some {B} are not {C}.", all_possible_conclusions),
     "OO2": ("Some {B} are not {A}.", "Some {C} are not {B}.", all_possible_conclusions),
     "OO3": ("Some {A} are not {B}.", "Some {C} are not {B}.", all_possible_conclusions),
     "OO4": ("Some {B} are not {A}.", "Some {B} are not {C}.", all_possible_conclusions),
}

# Add valid schema keys to invalid_schemas with complementary conclusions
for key, (prem1, prem2, valid_conclusions) in valid_schemas.items():
    if key not in invalid_schemas:
        invalid_conclusion_list = [c for c in all_possible_conclusions if c not in valid_conclusions]
        invalid_schemas[key] = (prem1, prem2, invalid_conclusion_list)

# Global dictionary containing all schema dictionaries
ALL_SCHEMAS = {
    'invalid_schemas': invalid_schemas,
    'valid_schemas': valid_schemas,
    'valid_plausible_diff_chain_C': valid_plausible_diff_chain_C,
    'valid_plausible_diff_chain_A': valid_plausible_diff_chain_A,
    'valid_plausible_same_chain': valid_plausible_same_chain,
    'invalid_plausible_same_chain': invalid_plausible_same_chain,
    'invalid_plausible_diff_chain_C': invalid_plausible_diff_chain_C,
    'invalid_plausible_diff_chain_B': invalid_plausible_diff_chain_B,
    'invalid_plausible_diff_chain_A': invalid_plausible_diff_chain_A,
    'invalid_plausible_diff_chain': invalid_plausible_diff_chain,
    'valid_implausible_same_chain': valid_implausible_same_chain,
    'valid_implausible_diff_chain_A': valid_implausible_diff_chain_A,
    'valid_implausible_diff_chain_B': valid_implausible_diff_chain_B,
    'valid_implausible_diff_chain_C': valid_implausible_diff_chain_C,
    'valid_implausible_diff_chain': valid_implausible_diff_chain,
    'invalid_implausible_same_chain': invalid_implausible_same_chain,
    'invalid_implausible_diff_chain_A': invalid_implausible_diff_chain_A,
    'invalid_implausible_diff_chain_B': invalid_implausible_diff_chain_B,
    'invalid_implausible_diff_chain_C': invalid_implausible_diff_chain_C,
    'invalid_implausible_diff_chain': invalid_implausible_diff_chain

}

count = 0
for curr_schema_key in ALL_SCHEMAS:
    curr_schema_val = ALL_SCHEMAS[curr_schema_key]
    per_schema_count = 0
    for syllogism in curr_schema_val:
        per_schema_count += len(curr_schema_val[syllogism][2])
        # print("  ", syllogism, ": ", len(curr_schema_val[syllogism][2]))

    print(curr_schema_key, ": ", per_schema_count)

    count += per_schema_count

print("Total count: ", count)